export const SIGN_UP_SUCCESS_ACTION = "SIGN_UP__SUCCESS_ACTION";
export const SIGN_IN_SUCCESS_ACTION = "SIGN_IN_SUCCESS_ACTION";
export const SIGN_UP_FAIL_ACTION = "SIGN_UP_FAIL_ACTION";
export const SIGN_IN_FAIL_ACTION = "SIGN_IN_FAIL_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
