export const GET_ALL_ROOMS="GET_ALL_ROOMS";
export const RETRIEVE_ROOM="RETRIEVE_ROOM";
export const UPDATE_ROOM="UPDATE_ROOM";
export const DELETE_ROOM="DELETE_ROOM";
export const CREATE_ROOM="CREATE_ROOM";