export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const GET_ALL_RESERVATIONS = "GET_ALL_RESERVATIONS";
export const RETRIEVE_RESERVATION = "GET_SINGLE_RESERVATION";
export const RETRIEVE_RESERVATIONS = "RETRIEVE_RESERVATIONS";
export const UPDATE_RESERVATION = "UPDATE_RESERVATION";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
